name: Apply terraform

inputs:
  ENVIRONMENT:
    required: true
    type: string
  CLIENT:
    required: true
    type: string
  COMPANY:
    required: true
    type: string
  WORKING_DIR:
    required: true
    type: string
secrets:
  AZURE_AD_CLIENT_ID:
    required: true
  AZURE_AD_CLIENT_SECRET:
    required: true
  AZURE_SUBSCRIPTION_ID:
    required: true
  AZURE_AD_TENANT_ID:
    required: true
env:
  CLIENT: ${{ inputs.CLIENT }}
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  COMPANY: ${{ inputs.COMPANY }}
  WORKING_DIR: ${{ inputs.WORKING_DIR }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Terraform Init
      id: init
      working-directory: ${{env.WORKING_DIR}}
      run: terraform init -backend-config=./env/${{env.CLIENT}}-${{env.ENVIRONMENT}}/backend.tfvars

    - name: Terraform Validate
      id: validate
      working-directory: ${{env.WORKING_DIR}}
      run: terraform validate
# TODO: create workflow for all branch
#      - name: Terraform Plan
#        id: plan
#        working-directory: ${{env.WORKING_DIR}}
#        run: terraform plan  -var-file=./env/${{env.CLIENT}}-${{env.ENVIRONMENT}}/terraform.tfvars

    - name: Terraform Apply
      id: apply
      working-directory: ${{env.WORKING_DIR}}
      run: terraform apply -var-file=./env/${{env.CLIENT}}-${{env.ENVIRONMENT}}/terraform.tfvars -auto-approve
