name: Apply terraform
description: Apply terraform module

inputs:
  ENVIRONMENT:
    required: true
    description: 'Which environment: dev, sit, stg, prod'
  CLIENT:
    required: true
    description: 'Which client: default, vrtp ...'
  WORKING_DIR:
    required: true
    description: 'Which terraform root folder to work with'
#secrets:
#  AZURE_AD_CLIENT_ID:
#    required: true
#  AZURE_AD_CLIENT_SECRET:
#    required: true
#  AZURE_SUBSCRIPTION_ID:
#    required: true
#  AZURE_AD_TENANT_ID:
#    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - shell: bash
      id: init
      working-directory: ${{env.WORKING_DIR}}
      run: terraform init -backend-config=./env/${{env.CLIENT}}-${{env.ENVIRONMENT}}/backend.tfvars

    - shell: bash
      id: validate
      working-directory: ${{env.WORKING_DIR}}
      run: terraform validate
# TODO: create workflow for all branch
#      - name: Terraform Plan
#        id: plan
#        working-directory: ${{env.WORKING_DIR}}
#        run: terraform plan  -var-file=./env/${{env.CLIENT}}-${{env.ENVIRONMENT}}/terraform.tfvars

    - shell: bash
      id: apply
      working-directory: ${{env.WORKING_DIR}}
      run: terraform apply -var-file=./env/${{env.CLIENT}}-${{env.ENVIRONMENT}}/terraform.tfvars -auto-approve
