name: Mirroring

on:
  workflow_call:
    inputs:
      REMOTE:
        required: true
        type: string
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
      AZURE_CREDENTIALS:
        required: true

env:
  K8S_NAMESPACE: ${{ inputs.K8S_NAMESPACE }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: ${{inputs.REMOTE}}
          GIT_USERNAME: spyoungtech
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
